name: Release pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Publish release to CDN
    runs-on: ubuntu-22.04
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Workaround checkout issues
        run: |
          git fetch --tags --force
      - name: Create Package
        uses: BigWigsMods/packager@v2
        with:
          args: -n "{package-name}-{project-version}"
      - name: Get package name
        run: | 
          echo "PACKAGE=$(find .release -type f -name *.zip -printf "%f\n")" >> $GITHUB_ENV
      - name: Publish package
        run: |
          curl https://api.tukui.org/v1/upload/$PACKAGE --upload-file .release/$PACKAGE -H "X-Tukui-Key: $DEPLOY_KEY" -H "Content-Type: application/zip"
